---
redmine_api_key: <REDMINE API KEY>
ldap_host: auth.forgeservicelab.fi
ldap_port: 636
ldap_bind_dn: cn=binder,ou=accounts,dc=forgeservicelab,dc=fi
ldap_bind_pw: <LDAP PASSWORD>
ldap_search_base: ou=accounts,dc=forgeservicelab,dc=fi
ldap_user_filter: '(|(memberof=cn=developers,ou=roles,dc=forgeservicelab,dc=fi)(memberof=cn=Digile.Platform,ou=projects,dc=forgeservicelab,dc=fi)(memberof=cn=CSC,ou=projects,dc=forgeservicelab,dc=fi)(memberof=cn=Kainuun.Etu,ou=projects,dc=forgeservicelab,dc=fi)(memberof=cn=Druid,ou=projects,dc=forgeservicelab,dc=fi))'
cas_url: "'https://auth.forgeservicelab.fi'"
service_email: admin@forgeservicelab.fi
gitlab_db_pass: <GITLAB DB PASSWORD>
github_app_id: <GITHUB APP ID>
github_app_secret: <GITHUB APP KEY>
