---
- name: Upload nginx configuration
  template:
    src: templates/gitlab.tpl
    dest: /etc/nginx/sites-available/gitlab
  notify: restart nginx

- name: Use alternative authorized_keys file for gitlab shell
  replace:
    dest: "{{ git_user_home }}/gitlab-shell/config.yml"
    regexp: ssh/authorized_keys
    replace: ssh/gitlab_authorized_keys

- name: Regenerate authorized_keys
  shell: echo yes | bundle exec rake gitlab:shell:setup RAILS_ENV=production
    chdir={{ git_user_home }}/gitlab
  sudo_user: "{{ git_user_name }}"

- name: Initialize database
  shell: echo yes | bundle exec rake gitlab:setup RAILS_ENV=production GITLAB_ROOT_PASSWORD={{ gitlab_admin_pass }}
    chdir={{ git_user_home }}/gitlab
  sudo_user: "{{ git_user_name }}"
  when: db_reinit

- name: Run database migration
  command: bundle exec rake db:migrate RAILS_ENV=production
    chdir={{ git_user_home }}/gitlab
  sudo_user: "{{ git_user_name }}"
  notify: restart gitlab
  tags:
    - redeploy

- name: Compile assets
  command: bundle exec rake assets:precompile RAILS_ENV=production
    chdir={{ git_user_home }}/gitlab
  sudo_user: "{{ git_user_name }}"
  notify: restart gitlab
  tags:
    - redeploy
