---
- hosts: all
  sudo: true
  vars_files:
    - group_vars/secrets.yml

  roles:
    - role: forge_ssl
      key_location: "{{ local_ssl_key_path }}"
      target_key_location: private/
      target_cert_location: certs/
    - role: gitlab

  tasks:
    - include: configure.yml
      vars:
        db_reinit: false
  post_tasks:
    - name: clear gitlab from /tmp directory
      file:
        path: /tmp/gitlab
        state: absent
  handlers:
    - name: restart gitlab
      service:
        name: gitlab
        state: restarted
