---
- hosts: all
  sudo: true
  vars_files:
    - group_vars/secrets.yml

  pre_tasks:
    - name: Create diffie-hellman strong parameters
      shell: openssl dhparam -out dhparam.pem 4096
        chdir=/etc/ssl/certs
        creates=/etc/ssl/certs/dhparam.pem
      async: 3600
      poll: 0
      register: dh_gen

    - name: Diffie Hellman progress
      async_status:
        jid: "{{ dh_gen.ansible_job_id }}"
      register: dh_job_result
      until: dh_job_result.finished
      retries: 360
      delay: 10

  roles:
    - role: gitlab
    - role: forge_ssl
      key_location: "{{ local_ssl_key_path }}"
      target_key_location: private/
      target_cert_location: certs/

  tasks:
    - include: configure.yml
      vars:
        db_reinit: false
  post_tasks:
    - name: clear gitlab from /tmp directory
      file:
        path: /tmp/gitlab
        state: absent
  handlers:
    - name: restart gitlab
      service:
        name: gitlab
        state: restarted
